### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by ghost** [GeneralMills/pytrends#135] opened 2017-06-05 13:50 UTC
Hi everybody, when I try to run the following script:
-------------------------------------------------------------------------------
 from pytrends.request import TrendReq

google_username = "myaccount@gmail.com"
google_password = "google_password"
path = ""

pytrend = TrendReq(google_username, google_password, hl='en-US', tz=360, custom_useragent=None)
pytrend.build_payload(kw_list=['pizza', 'bagel'])
interest_over_time_df = pytrend.interest_over_time()
interest_by_region_df = pytrend.interest_by_region()
related_queries_dict = pytrend.related_queries()
trending_searches_df = pytrend.trending_searches()
top_charts_df = pytrend.top_charts(cid='actors', date=201611)
suggestions_dict = pytrend.suggestions(keyword='pizza')
-------------------------------------------------------------------------------

I get this error:
-------------------------------------------------------------------------------
 Traceback (most recent call last):
  File "pytrends-usage.py", line 24, in <module>
    trending_searches_df = pytrend.trending_searches()
  File "/usr/lib/python2.7/site-packages/pytrends/request.py", line 201, in trending_searches
    req_json = json.loads(req.text)['trendsByDateList']
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
-------------------------------------------------------------------------------
Thanks in advantage.
Dandy

**Comment by manavkhandelwal** [comment] 2017-07-18 17:51
+1 having the same error. Any resolution?

**Comment by knatt3000** [comment] 2017-08-24 13:38
help

**Comment by dreyco676** [comment] 2017-08-25 18:47
Duplicate of #122. I'll continue the discussion there.

**Closed by dreyco676** 2017-08-25 18:47 UTC
