### ISSUE TITLE
JSONDecodeError even with updated timeframes

### ISSUE THREAD

**Issue by yudhvir** [GeneralMills/pytrends#125] opened 2017-04-09 09:33 UTC
```
pytrend = TrendReq("", "", hl='en-US', tz=360, custom_useragent="Chrome")
geo = 'US'
timeframe = 'now 7-d'
cat = 0
gprop = ''
pytrend.build_payload(['fidget'], timeframe=timeframe, geo=geo, gprop=gprop)
```

This throws the following error

```JSONDecodeError                           Traceback (most recent call last)
<ipython-input-7-c8ae85706aa1> in <module>()
      5 # except:
      6 #     print("LKJLSDFL")
----> 7 pytrend.build_payload(['fidget'], timeframe=timeframe, geo=geo, gprop=gprop)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pytrends/request.py in build_payload(self, kw_list, cat, timeframe, geo, gprop)
     79         token_payload['req'] = json.dumps(token_payload['req'])
     80         # get tokens
---> 81         self._tokens(token_payload)
     82         return
     83 

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pytrends/request.py in _tokens(self, token_payload)
     92         # strip off garbage characters that break json parser
     93         widget_json = req.text[4:]
---> 94         widget_dict = json.loads(widget_json)['widgets']
     95         # order of the json matters...
     96         first_region_token = True

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    352             parse_int is None and parse_float is None and
    353             parse_constant is None and object_pairs_hook is None and not kw):
--> 354         return _default_decoder.decode(s)
    355     if cls is None:
    356         cls = JSONDecoder

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py in decode(self, s, _w)
    337 
    338         """
--> 339         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    340         end = _w(s, end).end()
    341         if end != len(s):

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py in raw_decode(self, s, idx)
    355             obj, end = self.scan_once(s, idx)
    356         except StopIteration as err:
--> 357             raise JSONDecodeError("Expecting value", s, err.value) from None
    358         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I've tried changing the timeframes as suggested in the other issues, but to no avail. I also used TOR SOCKS proxy to route my traffic through different IPs, but still nothing.

**Comment by jeffreywu1996** [comment] 2017-05-11 00:53
Looks like syntax error.
`pytrend = TrendReq("", "", hl='en-US', tz=360, custom_useragent="Chrome", 
geo = 'US',
timeframe = 'now 7-d',
cat = 0,
gprop = '')
pytrend.build_payload(['fidget'], timeframe=timeframe, geo=geo, gprop=gprop)`

Should fix it.

**Comment by dreyco676** [comment] 2017-08-25 18:48
Duplicate of #122. I'll continue the discussion there.

**Closed by dreyco676** 2017-08-25 18:48 UTC
