### ISSUE TITLE
getting SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579) error

### ISSUE THREAD

**Issue by bigme666** [GeneralMills/pytrends#164] opened 2017-08-30 13:27 UTC
when I try to execute the example code I get the following error:

```
In [1]: from pytrends.request import TrendReq
   ...:

In [2]: pytrend = TrendReq()

In [3]: pytrend.build_payload(kw_list=['pizza', 'bagel'])
---------------------------------------------------------------------------
SSLError                                  Traceback (most recent call last)
<ipython-input-3-4a17a0b29512> in <module>()
----> 1 pytrend.build_payload(kw_list=['pizza', 'bagel'])

/home/b037865/projects/trends/lib/python2.7/site-packages/pytrends-4.2.2-py2.7.egg/pytrends/request.pyc in build_payload(self, kw_list, cat, timeframe, geo, gprop)
    105         self.token_payload['req'] = json.dumps(self.token_payload['req'])
    106         # get tokens
--> 107         self._tokens()
    108         return
    109

/home/b037865/projects/trends/lib/python2.7/site-packages/pytrends-4.2.2-py2.7.egg/pytrends/request.pyc in _tokens(self)
    116             method=TrendReq.GET_METHOD,
    117             params=self.token_payload,
--> 118             trim_chars=4,
    119         )['widgets']
    120

/home/b037865/projects/trends/lib/python2.7/site-packages/pytrends-4.2.2-py2.7.egg/pytrends/request.pyc in _get_data(self, url, method, trim_chars, **kwargs)
     64             response = requests.post(url, **kwargs)
     65         else:
---> 66             response = requests.get(url, **kwargs)
     67
     68         # check if the response contains json and throw an exception otherwise

/home/b037865/projects/trends/lib/python2.7/site-packages/requests/api.pyc in get(url, params, **kwargs)
     70
     71     kwargs.setdefault('allow_redirects', True)
---> 72     return request('get', url, params=params, **kwargs)
     73
     74

/home/b037865/projects/trends/lib/python2.7/site-packages/requests/api.pyc in request(method, url, **kwargs)
     56     # cases, and look like a memory leak in others.
     57     with sessions.Session() as session:
---> 58         return session.request(method=method, url=url, **kwargs)
     59
     60

/home/b037865/projects/trends/lib/python2.7/site-packages/requests/sessions.pyc in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    500         }
    501         send_kwargs.update(settings)
--> 502         resp = self.send(prep, **send_kwargs)
    503
    504         return resp

/home/b037865/projects/trends/lib/python2.7/site-packages/requests/sessions.pyc in send(self, request, **kwargs)
    610
    611         # Send the request
--> 612         r = adapter.send(request, **kwargs)
    613
    614         # Total elapsed time of the request (approximately)

/home/b037865/projects/trends/lib/python2.7/site-packages/requests/adapters.pyc in send(self, request, stream, timeout, verify, cert, proxies)
    512         except (_SSLError, _HTTPError) as e:
    513             if isinstance(e, _SSLError):
--> 514                 raise SSLError(e, request=request)
    515             elif isinstance(e, ReadTimeoutError):
    516                 raise ReadTimeout(e, request=request)

SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)
```

The only way I managed to make it work was to skip the ssl verification changing the lines from 64 to 66 in request.py as it follows:

```
 if method == TrendReq.POST_METHOD:
            response = requests.post(url, verify=False, **kwargs)
        else:
            response = requests.get(url, verify=False, **kwargs)
```
So doing I'm able to get the trends with the warning:  InsecureRequestWarning: 

`Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings`

my virtual env: python 2.7
```
 pip list

beautifulsoup4 (4.5.3)
certifi (2017.4.17)
chardet (3.0.4)
idna (2.5)
lxml (3.7.3)
numpy (1.12.0)
pandas (0.19.2)
pip (9.0.1)
progress (1.2)
python-dateutil (2.6.1)
pytrends (4.2.2)
pytz (2016.10)
requests (2.18.1)
setuptools (22.0.5)
six (1.10.0)
urllib3 (1.21.1)
wheel (0.29.0)
```

any hint? thank you.

**Comment by bigme666** [comment] 2017-08-30 14:56
solved setting

export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-bundle.crt

**Comment by dreyco676** [comment] 2017-08-30 15:02
Would you want to make a PR adding this to the documentation of known
caveats?

On Aug 30, 2017 09:56, "bigme666" <notifications@github.com> wrote:

solved setting

export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-bundle.crt

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/GeneralMills/pytrends/issues/164#issuecomment-326017108>,
or mute the thread

**Comment by bigme666** [comment] 2017-08-31 09:33
Of course I will

**Comment by dreyco676** [comment] 2017-09-22 17:19
Thanks for the PR. Closing issue.

**Closed by dreyco676** 2017-09-22 17:19 UTC

**Comment by pzh-tech** [comment] 2020-10-23 18:33
Thank you for the thread. 
I am still getting the following error even after I added "verify=False".  Also, I don't know where to add "export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-bundle.crt". thank you. 
SSLError: HTTPSConnectionPool(host='trends.google.com', port=443): Max retries exceeded with url: /?geo=GB (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),))

        if method == TrendReq.POST_METHOD:
            response = s.post(url, verify=False, timeout=self.timeout,
                              cookies=self.cookies, **kwargs, **self.requests_args)  # DO NOT USE retries or backoff_factor here
        else:
            response = s.get(url, verify=False, timeout=self.timeout, cookies=self.cookies,
                             **kwargs, **self.requests_args)

**Comment by Kkkassini** [comment] 2021-08-06 14:39
0 use
