### ISSUE TITLE
Issue with results returned

### ISSUE THREAD

**Issue by cdshinde** [GeneralMills/pytrends#83] opened 2016-11-12 03:40 UTC
Hello I am testing a comparision of 2 keywords. 
I tested it at my end "8.txt" and a fellow subordinate tested it in another location "pair 199.csv.txt".
If you see, in my csv the results have 0 in the results where as in the other 1 too and in the GT GUI result there are lot more 1's than 0's.

We have tested it with the same code different users.
The query parameter was => {'q': keyword, 'date': '04/2016 6m'}.

Why is there a discrepancy?
[8.txt](https://github.com/GeneralMills/pytrends/files/587038/8.txt).
[pair 199.csv.txt](https://github.com/GeneralMills/pytrends/files/587148/pair.199.csv.txt).
[multiTimeline.csv.txt](https://github.com/GeneralMills/pytrends/files/587161/multiTimeline.csv.txt) >> This one is generated by Google Trends UI. --> https://www.google.co.in/trends/explore?date=2016-04-01%202016-09-30,2016-04-01%202016-09-30&geo=,&q=cold%20shoulder%20jumpsuit,maxi%20dress

Please help.
Thanks in advance.

**Comment by candoz** [comment] 2016-11-13 12:57
There are two things going on, and nothing's wrong with the results:
1) It is known that same requests give slightly different data, see issue #45 and issue #76 
2) Data in "multiTimeline.csv" has a day-granularity instead of a week-granularity, so it's normal that it could be a little more precise, or just normalized differently

Anyway, both "0" and "1" values are too small to say anything in a study like that; my advice would be to compare two researches that are more similar in term of popularity: it's obvious fom your results that "cold shoulder jumpsuit" isn't comparable to "maxi dress".
Comparing "jumpsuit" to "maxi dress" for example could make more sense >>> https://www.google.co.in/trends/explore?date=2016-04-01%202016-09-30,2016-04-01%202016-09-30&geo=,&q=jumpsuit,maxi%20dress

Anyway, if you are really just interested in "cold shoulder jumpsuit" researches, do not compare them to anything else if you wanna see their trend more clearly >>> https://www.google.co.in/trends/explore?date=2016-04-01%202016-09-30&q=cold%20shoulder%20jumpsuit

**Comment by dreyco676** [comment] 2017-01-25 05:21
Duplicate of #45 Google changed their API and each one calculates slightly differently. We will be changing over to the new one but it will take time.

**Closed by dreyco676** 2017-01-25 05:21 UTC
