### ISSUE TITLE
Code 429. Login working?

### ISSUE THREAD

**Issue by xashgg** [GeneralMills/pytrends#239] opened 2018-05-19 18:10 UTC
Hi,

I'm new to programming and I may ask naive questions. I sent about 1000 request last night with 10s sleep time in between. Today, I got blocked after another 200 request.
According to the readme file, I can log in with my Google account to increase the quota. But I'm not sure how I should do that and I didn't find the corresponding argument in request.py file. Is it correct to use pytrends = TrendReq('usename', 'password') to login? Or is there any other walk-around? Thank you!

**Comment by dreyco676** [comment] 2018-05-29 19:32
Duplicate of #243

**Closed by dreyco676** 2018-05-29 19:32 UTC
