### ISSUE TITLE
No JSON Object Could be Decoded

### ISSUE THREAD

**Issue by manavkhandelwal** [GeneralMills/pytrends#144] opened 2017-07-18 17:49 UTC
Trying to get week-over-week data for keyword 'refinance' using PyTrends and this script was working really well until this morning when I got a "No JSON object could be decoded" error while building the payload. Any reason it would have stopped working now, or similar issues been seen?

```
GOOGLE_USERNAME = ""
GOOGLE_PASSWORD = ""
KW_LIST = ['refinance']

def run():
    frames1 = []
    if datetime.date.today().weekday() >= 5:
        adj = datetime.date.today() + datetime.timedelta(weeks=-1)
    else:
        adj = datetime.date.today()
    
    while(adj.weekday() != 4):
        adj = adj + datetime.timedelta(days=-1)

    for i in range(149,-1,-1):
        pytrend = TrendReq(GOOGLE_USERNAME,GOOGLE_PASSWORD,hl='en-US',tz=240,custom_useragent=None)
        print "{} iterations remaining.".format(str(i))

        date_second = adj + datetime.timedelta(weeks=(-1*i))
        date2 = date_second.strftime("%Y-%m-%d")
        
        date_first = date_second + datetime.timedelta(weeks=-12)
        while(date_first.weekday() != 5):
            date_first = date_first + datetime.timedelta(days=-1)
        date1 = date_first.strftime("%Y-%m-%d")

        dates = date1 + ' ' + date2

        # refinance 
        pytrend.build_payload(KW_LIST,timeframe=dates,geo='US')
        interests_over_time_rf = pytrend.interest_over_time()
        frames1.append(interests_over_time_rf)
        
    fullrfdata = pd.concat(frames1,axis=1)
    filename_rf = "F:\Code\Refinancing Model\Data\GT_refinance_" + adj.strftime("%m_%d_%y") + ".csv"
    f1 = open(filename_rf,'w')
    fullrfdata.to_csv(path_or_buf = f1)
    f1.close()
```

**Comment by dreyco676** [comment] 2017-08-25 18:47
Duplicate of #122. I'll continue the discussion there.

**Closed by dreyco676** 2017-08-25 18:47 UTC
