### ISSUE TITLE
Google Quota limit - IP Address changer 

### ISSUE THREAD

**Issue by jiby91** [GeneralMills/pytrends#77] opened 2016-11-03 18:33 UTC
Hi, 
As mentionned before in previous issues I face the Google quota limit after barely 10 requests. 
I tried to change my IP address by routing the requests through Tor. However I have not been able yet to bypass the limitation.
I raise the issue in the following page: http://stackoverflow.com/questions/40406458/google-trends-quota-limit-ip-address-changer

**Comment by samarv** [comment] 2016-11-04 06:36
Hey, 

I don't think IP rotation  will work, considering you are logging in on google. and from experience, I can tell you, google places limit on google ID's rather than IP. 

So, yeah login rotation with  multiple ID's can work. 
I am facing the same problem as asked in this question http://stackoverflow.com/questions/40404648/how-to-load-different-package-in-different-cluster-node-in-doparllel-r 

I will tell you, if i get to any solution!

**Comment by jiby91** [comment] 2016-11-04 10:35
I don't think Google limits my requests according to my google ID, because I have got the same issue when I don't input any google ID in the code. 

```
google_username= ""
google_password =""
```
Google might be able to guess what is my identity even if I change my IP and don't login.

**Comment by jiby91** [comment] 2016-11-04 16:40
I found the solution !
You need to reconnect for every new request with the command with a new **custom_useragent** :
`TrendReq(google_username, google_password, custom_useragent=randomName())`

In my case I created a random custom_useragent with the function randomName(). 
This function along with IP address changer and a time.sleep() seems to work for me.

**Comment by jiby91** [comment] 2016-11-04 17:27
If you are interested, you can find my program here, which I use to extract daily data for long time period (over 3 months) which is not possible. 
[https://github.com/jiby91/Daily-GoogleTrends-Data](url)

**Comment by candoz** [comment] 2016-11-04 20:31
Thanks for the advice, I'll try the Tor method if I need it before the connection bug is fixed!
I already use a random useragent, so I didn't think of that... But can you please mark as solved the stackoverflow question? I'll add the useragent detail to my answer where I suggested to use a new connection at every loop, if that's ok for you.
PS: I already implemented something for daily trend retrieval over many months of data, but I was curious of seeing your code; the link seems broken though.

**Comment by jiby91** [comment] 2016-11-04 22:05
I have updated the link. Please feel free to add any comment as I am not experienced in Python. 
I would be also interested in your code  for daily trend retrieval if you don't mind.

**Comment by candoz** [comment] 2016-11-04 22:30
I'll send you that part of my code via PM in the next days then.
The project is for my thesis (so it's not public for now) and the code is very work in progress, but that part seems to work fine, so it's not a problem to send it to anyone interested in it (I just have to add the 'Tor' part if the connection bug won't be fixed).

Going a little off-topic here, but I think it is necessary to specify that I download data in batches of three months, **overlapping one month between adjacent requests**: that's necessary to normalize the batches later; otherwise you have a different normalization every 3 months.

**Comment by jiby91** [comment] 2016-11-04 23:10
That's exactly what I do in my code, I only request batches of three months with one month overlapping and then I normalize the last batch with the values of the previous batch. 

No problem with sharing your code, actually this is also for my thesis ;)

**Comment by samarv** [comment] 2016-11-05 04:27
Hey, 

@jiby91  I saw your link, and I was wondering if you could share an example where your quota limit is not exceeded and you can query continuously.

**Comment by candoz** [comment] 2016-11-05 08:05
@jiby91 awesome! Good luck with your thesis then :D

**Comment by AJKlaholz** [comment] 2016-12-02 09:21
Hello Guys. I also need google trends for my thesis :P. My problem is, that I'm a noob in python. I only use the example script and added a few things. Most of all I use Java. Currently I also reconnect for every new request with the command with a new custom_useragent and  use time.sleep()(TimeUnit.SECONDS.sleep(30) in Java). But I dont know how to get a new IP address for every new request or use Tor in my java programm. Can you help me ?

**Comment by cwallac** [comment] 2017-01-05 22:42
How many requests were you able to succeed with in this? I'm attempting to get ~2500 per day.
I am using Tor to switch IP.
I have tried staying signed into one google account, I have tried swapping out google accounts, I have tried random words for Google accounts, I have tried no authorization. I still hit quota limits that I can't overcome after about 200 requests.

**Comment by knoteand** [comment] 2017-01-06 16:14
I'm facing similiar problems. We need to execute 1040 requests per Day for about 10 days.

Interestingly, the blockage does not affect the trends website when accessed through the browser (https://www.google.com/trends/), but it does affect the fetch url.

I couldn't find an easy way to isolate the necessary requests and authentications that are made, but there seems to be a token string generated for accesses through the official frontend. Also, the code generated for embedding can be modified and gives access to trend data, when added to a page.
It's pretty obscure beyond that.

I'm wondering if some browser automation could be used to open the official frontend and trigger the CSV download.

**Comment by samarv** [comment] 2017-01-07 08:19
@knoteand ,  I tried browser Automation! and I get Error 429, too many request. Even in BROWSER!

**Comment by knoteand** [comment] 2017-01-07 10:18
@samarv I've now setup Tor, using a random user agent and a different ip for each request (using empty credentials), and it works -- intermittently, requests will fail, but i assume this depends on the exit node chosen.

**Comment by cwallac** [comment] 2017-01-07 16:07
@knoteand how many requests have you succeeding at trying this?

**Comment by knoteand** [comment] 2017-01-07 16:27
@cwallac about 100 / hr. The script renews the tor circuit if a Quota or Rate error occurs. That gives about 5 requests per circuit. It's currently been running for about 1.5 hr and I hope it finishes in about 5 hr (584 queries remaining).

It should be noted that this approach is not really fair use, and there is only a limited amount of tor nodes out there. Not sure how fast this will waste them.

**Comment by dreyco676** [comment] 2017-01-25 05:07
Duplicate of #66 

https://github.com/GeneralMills/pytrends/issues/66

Google changed their API. I've identified a way to adapt pytrends but will take some time.

**Closed by dreyco676** 2017-01-25 05:07 UTC

**Comment by jcc10** [comment] 2018-02-20 18:31
I'm not re-opening, however, for those who come after: https://pypi.python.org/pypi/fake-useragent allows you to get random user-agents.
