### ISSUE TITLE
Is it just me or have 429 errors really increase these past few days?

### ISSUE THREAD

**Issue by igalci** [GeneralMills/pytrends#538] opened 2022-10-25 21:55 UTC
I used to get 429 error every time I request more than 6 items per hour or so.

But recently, especially today I am not able to request more than 1 per hour without getting 429. Is it just my IP acting up?

**Comment by edbarbier** [comment] 2022-10-26 11:04
Experiencing the same issue with the node library from @pat310 lately.

**Comment by CharlesFr** [comment] 2022-10-27 15:47
Any workarounds?

**Comment by ReemOmer** [comment] 2022-10-28 11:35
Same! the only workaround I was able to do is to re-run the code multiple times in different machines or using colab with different account.

**Comment by firmai** [comment] 2022-10-28 12:50
Same here, they are locking down folks.

**Comment by royherma** [comment] 2022-10-29 14:27
How is there no reliable solution for this in 2022 😢

**Comment by emlazzarin** [comment] 2022-10-29 16:03
Supporting an external API for Google Trends isn't a priority for Google.

**Comment by Arsh1219** [comment] 2022-10-31 02:45
Not facing the issue after using proxies and sleep 60 seconds after each request.

**Comment by CharlesFr** [comment] 2022-10-31 08:03
> Not facing the issue after using proxies and sleep 60 seconds after each request.

Do you mind sharing where you're getting proxy from and how you're implementing them?

**Comment by Arsh1219** [comment] 2022-10-31 08:09
> > Not facing the issue after using proxies and sleep 60 seconds after each request.
> 
> Do you mind sharing where you're getting proxy from and how you're implementing them?

I’m using proxies from newipnow. I’m using 25 proxies and using random proxy on each request.

**Comment by CaCaBlocker** [comment] 2022-10-31 23:54
Hi, @Arsh1219 
I was trying to use the random proxies to scrape the Google trends. Sometimes, it worked well, but sometimes, it didn't with 429 error. **One thing what I want to tell you is that I sent 100 requests at once without delay**. How do you think it is the reason? How could you insist this statement - "Not facing the issue after using proxies and sleep 60 seconds after each request."?
Hope for your reply.

**Comment by ReemOmer** [comment] 2022-11-01 04:57
Guys, I just figured that if you downgrade the pytrend library to 4.7.2 or 4.7.3 it works. Also, collecting data for different geographical locations may stop the process, use only one location at a time, with up to 5 keywords.

**Comment by ReemOmer** [comment] 2022-11-01 04:59
For more than 5 keywords, you need to apply normalization, and that is by using one shared keyword as a control in all sets of 5 keywords.

**Comment by ReemOmer** [comment] 2022-11-01 05:20
Alternatively, you may want to try R instead of Python: https://cran.r-project.org/web/packages/gtrendsR/gtrendsR.pdf
This is a recent release of this month; it is more recent and reliable to use.

**Comment by jhascall** [comment] 2022-11-01 05:21
> Guys, I just figured that if you downgrade the pytrend library to 4.7.2 or 4.7.3 it works. Also, collecting data for different geographical locations may stop the process, use only one location at a time, with up to 5 keywords. For more than 5 keywords, you need to apply normalization, and that is by using one shared keyword as a control in all sets of 5 keywords.

This worked for me! Thanks for the fix!

**Comment by jhascall** [comment] 2022-11-01 16:00
> > Guys, I just figured that if you downgrade the pytrend library to 4.7.2 or 4.7.3 it works. Also, collecting data for different geographical locations may stop the process, use only one location at a time, with up to 5 keywords. For more than 5 keywords, you need to apply normalization, and that is by using one shared keyword as a control in all sets of 5 keywords.
> 
> This worked for me! Thanks for the fix!

Update: now it doesn't work... It only took 12 hours for them to block it

**Comment by igalci** [comment] 2022-11-01 16:11
> Guys, I just figured that if you downgrade the pytrend library to 4.7.2 or 4.7.3 it works. Also, collecting data for different geographical locations may stop the process, use only one location at a time, with up to 5 keywords. For more than 5 keywords, you need to apply normalization, and that is by using one shared keyword as a control in all sets of 5 keywords.

Where do you find version 4.7.x?  I only see 4.8.0 now. From which date was it?

**Comment by ReemOmer** [comment] 2022-11-03 04:49
It is still working for me! try to increase the sleep time between requests for each subset of keywords (I use random number between 5 and 30 seconds wait). Also, don't use only one machine with the same IP address, alternate between your machine and Google Colab.

**Comment by emlazzarin** [comment] 2022-11-03 07:29
Is it working because you downgraded or because your querying strategy has changed?

**Comment by ReemOmer** [comment] 2022-11-03 07:46
Both! I figured that even if I downgraded and sent too many requests, Google may block my IP, therefore, I had to change the IP this can be done by using proxies, vpn, Google Colab has also different range of IPs.

**Comment by emlazzarin** [comment] 2022-11-03 08:00
How do you know the downgrade is the cause of success? Could you help identify any changes?

**Comment by igalci** [comment] 2022-11-03 15:46
@ReemOmer  I am curious, how do you use Google Colab to scrape? I don't believe they have an API... And I haven't found any guide like that....

**Comment by ReemOmer** [comment] 2022-11-07 04:54
@emlazzarin honestly I didn't open any of the main files in both versions, so I don't know what the difference is.
@igalci I used the same way of running the code in Jupyter notebook or a regular Python file run using the cmd. You will still use the Pytrends library and call all its functions.

**Comment by regionalecon** [comment] 2022-11-08 20:08
I have an extremely novice understanding of the inner-workings of the package, but could this problem have something to do with cookies expiring on the trends.google site? I previously have been able to workaround 429 errors with [this solution](https://stackoverflow.com/questions/50571317/pytrends-the-request-failed-google-returned-a-response-with-code-429/50616233#50616233) but now that doesn't work either. Scrolling through the request headers, I noticed a cookie expiration time that ends in the same minute as submitting the request.

**Comment by xenova** [comment] 2022-12-04 23:03
Looks like no user-agent is specified in the requests, meaning they are blocked more often. I fixed it here: https://github.com/GeneralMills/pytrends/commit/18f230dd69c2cd89c203c967ac139a8218975f4d

**Comment by emlazzarin** [comment] 2022-12-26 18:16
Fixed by #553.

**Closed by emlazzarin** 2022-12-26 18:16 UTC
