### ISSUE TITLE
Type inconsistencies in returned DataFrame

### ISSUE THREAD

**Issue by cglacet** [GeneralMills/pytrends#399] opened 2020-06-01 14:55 UTC
There are type inconsistencies in the returned object (for now I only saw that on the `isPartial` column).

Using `timeframe='all'`: 

```python
value                int64
isPartial            object
```

Using `timeframe='today 3-m'`: 

```python
value                int64
isPartial            bool
```

Quickfix in the mean time: 

```python
if df['isPartial'].dtypes != np.bool:
    df['isPartial'] = df['isPartial'].map({'False': False, 'True': True})
```

**Comment by MaxGhenis** [comment] 2020-06-09 14:51
Duplicate of https://github.com/GeneralMills/pytrends/issues/353

**Closed** 2020-06-16 19:28 UTC
