### ISSUE TITLE
"ValueError: year is out of range"

### ISSUE THREAD

**Issue by fcbuss** [GeneralMills/pytrends#120] opened 2017-03-11 21:33 UTC
Today I installed pytrends and got this error: ValueError: year is out of range
The same as described here:
http://stackoverflow.com/questions/42601863/python-for-google-trends-valueerror-year-is-out-of-range-when-using-interest/42738181#42738181

I fixed it in the that way in python...\Lib\site-packages\pytrends\request.py

Added in the head:
from datetime import datetime

Changed around Line 128:
#df['date'] = pd.to_datetime(df['time'],unit='s')
df['date'] = df['time'].map(lambda d: datetime.fromtimestamp(int(d)))

Can this be included in the main framework?

**Comment by erood** [comment] 2017-04-14 18:09
Is this fix still working for you? Having the same issue and tried your fix to no avail

**Comment by dreyco676** [comment] 2017-08-25 21:06
I'm not able to reproduce on my side so it may have gotten fixed by changing Google endpoints. Reopen if persists.

**Closed by dreyco676** 2017-08-25 21:06 UTC
