### ISSUE TITLE
Data differs from web when multiple-word keywords

### ISSUE THREAD

**Issue by rafrodriguez** [GeneralMills/pytrends#76] opened 2016-10-31 21:09 UTC
What is the expected behavior when a keyword has multiple words? (I don't mean multiple keywords per query)

I tested for example with
 `payload['q'] = 'house rent'`

And the retrieved data differs from that of the web interface.

Thank you.

**Comment by candoz** [comment] 2016-11-07 11:50
Hello!
How much does it differ? 
It is known that Google Trends queries give "slightly" different data for different requests (see issue #45).
This is true for requests composed by both single words and multiple words.
Here you can see a graph I made for the same request done in three different dates with PyTrends api:

![401k_reinforcement](https://cloud.githubusercontent.com/assets/9741596/20056476/98f8d994-a4e6-11e6-8110-61da084f9f03.png)
The black line is the mean of the three requests values, I've done it to strengthen the retrieved data.

The only doubt that I still have regarding this issue is that same consecutive requests done manually in the same day seems to return the same values, but that's not true for automated requests done with PyTrends api.
Maybe it's because Google caches older recent requests for the same user, but he can't do that with PyTrend because there's an authentication bug at the moment (see issue #74).
I'm just guessing some possibilities here, I'd really like to hear other opinions.

**Comment by dreyco676** [comment] 2017-01-25 05:09
Duplicate of #45 https://github.com/GeneralMills/pytrends/issues/45

Google changed their API, so the new page you see on the web is calculating things differently. I will be switching pytrends to the new API but it will take time.

**Closed by dreyco676** 2017-01-25 05:09 UTC
