### ISSUE TITLE
Data differs from web interface

### ISSUE THREAD

**Issue by burakuyar** [GeneralMills/pytrends#45] opened 2016-08-16 13:41 UTC
Hi,
Firstly, thanks for the module.

I've fetched some data using the module but when I check it against the csv taken manually, there are some differences in the numbers.
For example: keyword: "olympics", time: "today 30-d"
data for 14.08.2016 is 100(manual) and 86(from api).

Am I missing something or can you reproduce results this as well?

Thanks in advance.

**Comment by dreyco676** [comment] 2016-08-29 01:41
I've eliminated fake-user agent in 1.2.0 which might have been setting your location to another geo-graphical area (US) than your home location when you manually use the browser. 

Please let me know if this is still an issue.

**Comment by Nzteb** [comment] 2016-09-19 19:20
I do have the same issue. How is this possible? Does the data provided in the US differ from the data provied in Europe?

**Comment by dreyco676** [comment] 2016-09-19 19:33
It is indexed by the number searches in the geographic region you filter it to, therefore the numbers would be different. You can set it to worldwide.

**Comment by Nzteb** [comment] 2016-09-20 18:16
My problem is that the data differ, even if _exactly the same_ parameters are entered in the module and the web interface respectively.

E.g I call:

 _trend({'q':'pizza','date': '1/2014 12m','geo':'US'}, 'dataframe')_

The first value of the returned dataframe is: 

2014-01-05   78.0

But when I go to Google Trends and in the menu I choose: United States, 2014 and then enter 'pizza' (search term), the value of the first node is:

05 Jan - 11 Jan: 79

The difference gets even higher for the following nodes and I dont see, why these can be different?

Interestingly I found following weird appearance: I checked the url that is requested by the module.
(I changed export to '5' so you can see tha graph, it has no effect on the data)

https://www.google.com/trends/fetchComponent?cid=TIMESERIES_GRAPH_0&date=1%2F2014+12m&q=pizza&export=5&geo=US

The graph shows the data, that is generated by the module. On the right bottom of the page there is a link that says 'View full report in Google Trends'. By clicking this link you reach the web interface of Google Trends with the parameteres already put in the menu. But the data differ to the data on the page before! Do you see the difference?

It would be very nice if you could help me with that.

Thank you.

**Comment by dreyco676** [comment] 2016-09-20 18:34
If you download the CSV from the link on the chart you shared you will see
that the date ranges do not line up. One starts at Jan 5th, the other
starts at Jan 4th.

**Comment by Nzteb** [comment] 2016-09-20 19:20
Thank you but I dont see this. When I download the CSV from Google Trends it starts at 5.Jan. I dont see that there could be a different CSV to download. The chart as well as the dataframe from the module says the range starts at 5. Jan, too. Could you show me an example where the data from the module exactly fit the data obtained by Google Trends?

**Comment by dreyco676** [comment] 2016-09-20 20:03
- I go to the link you sent. The first point is Jan 5th - 11th 2014, the data value is 78.

- I click on the link in the corner "View full report in Google Trends" That one also says Jan 5th - 11th 2014 but the data value is 79. 

- I click on the drop down and download to CSV. The first row says 2014-01-04, value 79.

My guess is Google is doing one inclusive of the date on visualization, and exclusive of the date on the other. Since the data is indexed it will be sensitive to the inclusive or exclusion of that date.

If I request the actual K,V data from Google Trends or inspect the JSON in the page source from the link you shared I'll see {"v":new Date(2014,0,5),"f":"Jan 4 \u2013 11, 2014"},{"v":78.0,"f":"78"} for the first record. Which looks like an error on Google's part because they are creating a new date Jan 5th for Jan 4th values.

**Comment by Nzteb** [comment] 2016-09-21 18:31
Thank you for going into this.

> - I click on the drop down and download to CSV. The first row says 2014-01-04, value 79.

When I change my computer settings to an US timezone and re-log in into Google, the first row says _2014-01-04, value 79_ , too. With Central Europe timezone settings (as in my last posts) it says _2014-01-05, value 79_ .

>My guess is Google is doing one inclusive of the date on visualization, and exclusive of the date on the other. Since the data is indexed it will be sensitive to the inclusive or exclusion of that date.

Yes, that sounds plausible. Yet we still dont know for sure which periods have been used for which type of data (Google Interface vs. Module/Json) because the Json has both dates in it as well. And I really need to fetch data with the module, that can exactly be replicated from the Google Interface, so Iam still curious about if that is possible?


>- I go to the link you sent. The first point is Jan 5th - 11th 2014, the data value is 78.

Well, yes but... what is going on here:  
When I click the link again (it is one day later now), the value is not **78 anymore but it changed to 77?!** (And of course the same with requesting it with the pytrends module) I know that the interpretation of the data is not affected much in general because the relation between single datapoints is only weakly changed (indexing). Still, if the data fetched today for a specific period differs from the data fetched tomorrow for the same period, Iam wondering how exactly the data is created and if I can use it for research. What is it, that I am missing?

**Comment by shobute** [comment] 2016-09-27 08:49
I have been researching this as I have also been having the same problem.

This comment on a different project may be relevant: https://github.com/PMassicotte/gtrendsR/issues/117#issuecomment-243438040

**Comment by samarv** [comment] 2016-09-28 08:55
hey people, Something weird is happening when i pull data for last week by this code
```
trend_payload = {'q': x, 'cat': '0-71','date': 'today 7-d','tz': 'GMT+5'}
   df = pytrend.trend(trend_payload, return_type='dataframe')
```

when I download the data through CSV, i have 168 rows, when i download data from pytrends library there are 153 rows!  and data points don't match at all! they follow the trend but they are all over the place! seems like a geo location issue, though i have kept both of my locations as World . 

Btw, I also use https://github.com/PMassicotte/gtrendsR and it works, shows data exactly as web downloaded CSV 

there's something wrong! really appreciate your help!

**Comment by Nzteb** [comment] 2016-10-02 10:22
Thank you for the link. The comment clears up some questions. I observed  the GTrends interface data on different days and it turns out that they are not consistent either. As the comment supposes, the difference seems to be higher for non-frequent search terms. If the reason for the inconsistency is caused by different samples, this probably can be fixed by fetching the same data at different days and averaging them and therefore getting lower variance of the 'estimate'.

The question now is if the difference between GTrends interface and the link I posted (again: which is used to provide the pytrends module data)  has the same reason. If so, it would be fine. But there is still some uncertainty in it I think.

**Comment by nartz** [comment] 2016-10-17 23:55
Hi - i'm facing the issue of the web interface returning much different values than this API. I'm searching for the term 'eye drops' filtered to the US-CO (colorado) geo: 

web interface: https://www.google.com/trends/explore?date=all&geo=US-CO&q=eye%20drops
pytrends: 
trend_payload = {
    'q': 'eye drops',
    'geo': 'US-CO',
}

The data returned from pytrends has a lot of 0 values at the start you can see (i.e. jan 2004).

I noticed that the web UI is hitting a url like:
parsed params:
```
hl:en-US
tz:360
req:{"time":"2004-01-01 2016-10-17","resolution":"MONTH","locale":"en-US","comparisonItem":[{"geo":{"region":"US-CO"},"complexKeywordsRestriction":{"keyword":[{"type":"BROAD","value":"eye drops"}]}}],"requestOptions":{"property":"","backend":"IZG","category":0}}
```

url:
`https://www.google.com/trends/api/widgetdata/multiline?hl=en-US&tz=360&req=%7B%22time%22:%222004-01-01+2016-10-17%22,%22resolution%22:%22MONTH%22,%22locale%22:%22en-US%22,%22comparisonItem%22:%5B%7B%22geo%22:%7B%22region%22:%22US-CO%22%7D,%22complexKeywordsRestriction%22:%7B%22keyword%22:%5B%7B%22type%22:%22BROAD%22,%22value%22:%22eye+drops%22%7D%5D%7D%7D%5D,%22requestOptions%22:%7B%22property%22:%22%22,%22backend%22:%22IZG%22,%22category%22:0%7D%7D&tz=360`

whereas pytrends is hitting `/trends/fetchComponent` url. Has something changed? Does trends have a new API url?

**Comment by dreyco676** [comment] 2016-10-19 15:12
When I've got time I may re-release a temporary branch using the previous method of getting the data which is much clunkier, but apparently works.... If some one wants to get a headstart on that they can look at the version before v3.0

**Comment by dreyco676** [comment] 2017-01-25 05:26
Google trends API changed. They are calculated differently. I will switch over to the new API soon but it will take time.

**Closed by dreyco676** 2017-01-25 05:26 UTC
