### ISSUE TITLE
You have reached your quota limit

### ISSUE THREAD

**Issue by NJBaker** [GeneralMills/pytrends#68] opened 2016-09-29 22:02 UTC
Has anyone else run into the following when establishing the connection? 

**You have reached your quota limit.  Please try again later.**

This is after doing zero requests in the last 20 hours, so I'm not sure if it is related to possibly hitting trends too hard in a previous session or if this is a cookie issue.

I've attempted to establish a connection using proxies and different accounts and I get the same response back from the connector every time.

Any thoughts?

**Comment by dreyco676** [comment] 2016-10-19 15:15
Hmm others have been having trouble with the quota limit recently as well. I'm not 100% sure that the cookies/session is getting passed correctly to google and so it may still be thinking you are anonymous. If this is a big issue stopping work, check out a version before v3.0

**Comment by nartz** [comment] 2016-10-20 03:32
After much trial and error (different accounts, proxy servers, sleep time at 10 seconds) - I figured out that re-logging in, i.e. `pytrends = TrendReq(google_username, google_password, custom_useragent=None)` before every request or every few requests, along with a 10 second sleep allowed me to successfully make many requests. Without re-logging, I would assuredly get banned after 12 requests to trend().

**Comment by samarv** [comment] 2016-10-24 12:21
Hey @nartz , can you please share the code, that allows many calls.

**Comment by roune** [comment] 2016-10-24 15:05
The core of the problem arrives when Google detects we are not using cookies. Even if you try changing the user agent, you will find a problem with the quota limit. When you arrive to the max and you try to download manually with the same account, Google Trends does not give you any error. So we just need to save the cookies gotten with the login and then send them back with the requests.
Unfortunately, I do not currently have the level of python to help this library.

**Comment by candoz** [comment] 2016-10-25 21:02
So that's why I was having so much trouble with it lately! I thought that Google had just heavily reinforced his controls and limitations against bots.
I used your API in April and I remember that I did something like 1500 requests per day with no problem.
I'm trying the new version for some weeks now and I'm constantly getting the "Quota limit" error; that's a pity, because I love the new version, especially the error handling.
I really hope that someone could fix the cookies/session bug somehow (that would be awesome), otherwise thank you all anyway for your great work.

Ah yes, I also tried using multi-user, multi-login, multi-request, etc. method. 
Some days it has worked better than others. Now I just have to reset my mobile data connection every few requests to keep it going.

**Comment by mhoover** [comment] 2016-12-20 22:16
I was running into a similar issue as @NJBaker with the `You have reached your quota limit. Please try again later.` but then submit another request immediately after and not have a problem. When I went through a little more deeply, I was making a request that wasn't returning data and the text coming back included the HTML class tag `errorSubTitle` with the text `You have reached your quota limit. Please try again later.` [Since this](https://github.com/GeneralMills/pytrends/blob/master/pytrends/request.py#L64) checks if `You have reached your quota limit. Please try again later.` is in the return and it was true, it was raising the quota limit error, though it was a red herring. Very likely unrelated to others issues, but thought worth raising in case this is causing confusing behavior for others.

**Comment by dreyco676** [comment] 2017-01-25 05:07
Duplicate of #66 

https://github.com/GeneralMills/pytrends/issues/66

Google changed their API. I've identified a way to adapt pytrends but will take some time.

**Closed by dreyco676** 2017-01-25 05:07 UTC

**Comment by roune** [comment] 2017-01-26 14:33
If needed I could help you out to implement it

**Comment by dreyco676** [comment] 2017-01-26 14:50
I'd love that. Check out the other branch. Basically I have the web requests working properly I just need to build out the parsers.
