### ISSUE TITLE
pytrends_v.4.1.3 - ConnectionError -- CertificateError

### ISSUE THREAD

**Issue by crosa418** [GeneralMills/pytrends#149] opened 2017-08-01 02:17 UTC
I just downloaded your branch v.4.1.3 and installed using pip install.  

```
from pytrends.request import TrendReq
google_username = ''
google_password = ''
pytrend = TrendReq(google_username, google_password, custom_useragent='pytrends')
pytrend.build_payload(kw_list=['pizza', 'bagel'] , geo = 'IN')
```

Everything runs fine up to line 4, but when I execute line 5, I get the following error
```ConnectionError: HTTPSConnectionPool(host='trends.google.com', port=443): Max retries exceeded with url: /trends/api/explore?property=&req=%7B%22comparisonItem%22%3A+%5B%7B%22geo%22%3A+%22%22%2C+%22keyword%22%3A+%22pizza%22%2C+%22time%22%3A+%22today+5-y%22%7D%2C+%7B%22geo%22%3A+%22%22%2C+%22keyword%22%3A+%22bagel%22%2C+%22time%22%3A+%22today+5-y%22%7D%5D%2C+%22category%22%3A+0%7D&tz=360&hl=en-US (Caused by SSLError(CertificateError("hostname 'trends.google.com' doesn't match 'www.google.com'",),))```

It seems that I am getting a certificate error that I cannot resolve.  I tried to upgrade my requests and httpie packages using `pip install --upgrade requests[security] | pip install --upgrade httpie` and still get the same error.  

Anyone know why this is happening and/or how to fix it?

**Comment by dreyco676** [comment] 2017-08-25 18:50
Could it be a possible duplicate of #109?

**Comment by dreyco676** [comment] 2017-08-25 20:22
I got rid of authentication altogether so I'm hoping that resolves the issue.

**Closed by dreyco676** 2017-08-25 20:22 UTC
