### ISSUE TITLE
JSONDecodeError: Expecting value

### ISSUE THREAD

**Issue by yurismine** [GeneralMills/pytrends#124] opened 2017-04-03 14:22 UTC
Hi,

I installed setup.py and simply ran example.py. An error came out as follows:

Traceback (most recent call last):

  File "<ipython-input-14-43e72727c63e>", line 1, in <module>
    runfile('E:/data/fnarita/LICtrends/examples/example.py', wdir='E:/data/fnarita/LICtrends/examples')
  File "d:\apps\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)
  File "d:\apps\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "E:/data/fnarita/LICtrends/examples/example.py", line 32, in <module>
    trending_searches_df = pytrend.trending_searches()
  File "d:\apps\Anaconda3\lib\site-packages\pytrends\request.py", line 201, in trending_searches
    req_json = json.loads(req.text)['trendsByDateList']
  File "d:\apps\Anaconda3\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "d:\apps\Anaconda3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "d:\apps\Anaconda3\lib\json\decoder.py", line 357, in raw_decode
    **raise JSONDecodeError("Expecting value", s, err.value) from None**

**JSONDecodeError: Expecting value**

Anyone by any chance know how to fix this problem? Thanks.

**Comment by pbwilmot** [comment] 2017-04-11 00:28
The trending_searches and top_charts endpoints both seem to be deprecated and/or changed.

So if you comment out both
```
trending_searches_df = pytrend.trending_searches()
```

and

```
top_charts_df = pytrend.top_charts(cid='actors', date=201611)
```

from the example.py file then you will be able to run this file for the other queries

**Comment by LEON-MING** [comment] 2017-07-28 15:33
Hello,

I don't know if this issue is still relevant, but I thought I might comment since I ran into what seemed like the same problem.
I ended up getting something to work for my purposes by modifying the request urls in request.py:

    def trending_searches(self):
        """Request data from Google's Trending Searches section and return a dataframe"""

        # make the request
        req_url = "https://trends.google.com/trends/hottrends/hotItems"
        forms = {'ajax': 1, 'pn': 'p1', 'htd': '', 'htv': 'l'}
        req = self.ses.post(req_url, data=forms)
        req_json = json.loads(req.text)['trendsByDateList']
        result_df = pd.DataFrame()

        # parse the returned json
        for trenddate in req_json:
            sub_df = pd.DataFrame()
            sub_df['date'] = trenddate['date']
            for trend in trenddate['trendsList']:
                sub_df = sub_df.append(trend, ignore_index=True)
        result_df = pd.concat([result_df, sub_df])
        return result_df

    def top_charts(self, date, cid, geo='US', cat=''):
        """Request data from Google's Top Charts section and return a dataframe"""

        # make the request
        # create the payload
        chart_payload = {'ajax': 1, 'lp': 1}
        chart_payload['geo'] = geo
        chart_payload['date'] = date
        chart_payload['cat'] = cat
        chart_payload['cid'] = cid
        req_url = "https://trends.google.com/trends/topcharts/chart"
        req = self.ses.post(req_url, params=chart_payload)

        # parse the returned json
        req_json = json.loads(req.text)['data']['entityList']
        df = pd.DataFrame(req_json)
        return df

All I did was change www.google.com to trends.google.com--did not expect it to work. I'm not sure if this is a real fix, but it worked for what I needed.

As a side note, thank you to the creators and maintainers of this repo!

**Comment by dreyco676** [comment] 2017-08-25 18:48
Duplicate of #122. I'll continue the discussion there.

**Closed by dreyco676** 2017-08-25 18:48 UTC
